### ISSUE TITLE
canotto90_chrome-push-notifications.js:60 Unable to subscribe to push. DOMException: Registration failed - manifest empty or missing keeps on coming

### ISSUE THREAD

**Issue by erhimanshugoyal** [taromero/meteor-chrome-push-notifications#2]
Hi , I am new to Meteor

Have both the manifest.json and service-worker.js in the public directory, but it breaks on 

console.error('Unable to subscribe to push.', e)

**Comment by taromero** [comment]
Hi, please provide the full stack-trace and a link to the project, to see if I'm able to help.
