### ISSUE TITLE
canotto90_chrome-push-notifications.js  : canotto90_chrome-push-notifications.js?hash=7100bef…:95 Unable to subscribe to push. DOMException: Registration failed - missing applicationServerKey, and manifest empty or missing

### ISSUE THREAD

**Issue by Bhumikathiriya** [taromero/meteor-chrome-push-notifications#3]
Hi,
 
I m using canotto90:chrome-push-notifications package for browser push notification.I follow the steps as per documentation.But when I checked push notification check box,it gives the error as below:

**Comment by taromero** [comment]
Closing this as this project is not maintained anymore.
