### ISSUE TITLE
canotto90_chrome-push-notifications.js : Unable to subscribe to push. DOMException: Registration failed - missing applicationServerKey, and manifest empty or missing

### ISSUE THREAD

**Issue by Bhumikathiriya** [taromero/meteor-chrome-push-notifications#4]
Hi,
 
I m using canotto90:chrome-push-notifications package for browser push notification.I follow the steps as per documentation.But when I checked push notification check box,it gives the error as below:

canotto90_chrome-push-notifications.js?hash=7100bef…:95 Unable to subscribe to push. DOMException: Registration failed - missing applicationServerKey, and manifest empty or missing.

I put the mainfest.json and service-worker.js in my public folder.

**manifest.json**

{
  "gcm_sender_id": "xxxxxxxxxxx",
  "gcm_user_visible_only": true
}

**service-worker.js**

self.addEventListener('push', showNotification)
self.addEventListener('notificationclick', closeNotificationAndOpenWindow)

function showNotification(event) {
  console.log('Received a push message', event)

  var title = 'Yay a message.'
  var body = 'We have received a push message.'
  var icon = '/images/icon-192x192.png'
  var tag = 'simple-push-demo-notification-tag'

  event.waitUntil(
    self.registration.showNotification(title, {
    body: body,
    icon: icon,
    tag: tag
  })
  )
}

function closeNotificationAndOpenWindow(event) {
  console.log('On notification click: ', event.notification.tag)
  // Android doesn’t close the notification when you click on it
  // See: http://crbug.com/463146
  event.notification.close()

  // This looks to see if the current is already open and
  // focuses if it is
  event.waitUntil(clients.matchAll({
    type: "window"
  }).then(function(clientList) {
    for (var i = 0; i < clientList.length; i++) {
      var client = clientList[i]
      if (client.url == '/' && 'focus' in client)
        return client.focus()
    }
    if (clients.openWindow)
      return clients.openWindow('/')
  }))
}

Is there in mistake in these files?

Can you suggest the solution?

Thanks.

**Comment by taromero** [comment]
Closing this as this project is not maintained anymore.
